# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ff9e50b7b780bca7e4257e096b033b810d8567bc88ad28a83bc68e2c9f67f8fbf4a297747cf3f64e5db8a567b9c9987f5b980a29b015e71cbf5dc41f49ec960

test:
  secret_key_base: 9aa9d4575ac9500cccc455dcfdb76dcae3a318f8da65129374743fac53dc2db0ec97b6c07a1250b77c6a16d60fb48fcc087297a890fbb65dbdb1ed224ac4b864

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
